Cohort 2/participants/template.md, README.md, code-of-code.md, faq.md
=> add link to WiEP handbook, update structure

Cohort 2/participants/TC.md
Adding TC into the participant list
=> Add TC intro

Cohort 2/participants/marlene.md
add Marlene in the participant list
=> add Marlenes intro

Cohort 2/participants/ijay.md
=> Add Ijay introduction

Cohort 3/1-sessions-tracker.md, Cohort 3/2-progress-tracker.md
This PR provides links to Week-1 Opening Ceremony agenda, recording, materials and home assignment, Week-2 issue (agenda).
=> Add week-1 links, week-2 issue

Cohort 3/2-progress-tracker.md
=> DOREEN: Cohort 3 Week 2 .

Cohort 3/2-progress-tracker.md
=> Odinga Valery: Cohort 3 week 2

Cohort 3/2-progress-tracker.md
=> Cheryl Owala: Cohort 3 Week 2

Cohort 3/2-progress-tracker.md
=> LOISA-MBURU: Cohort 3 week 2

Cohort 3/2-progress-tracker.md
=> Lada: Cohort 3 Week 2

Cohort 3/2-progress-tracker.md
Added myself to the progress tracker table with my github repo link
I had the impression that the table is alphabetically ordered, so I placed myself at the top, but if that is wrong, I can change it.
=> Asli: Cohort 3 Week 2 Assignment

Cohort 3/2-progress-tracker.md
=> ODINGA: Cohort 3 week 3 Assignment.

Cohort 3/2-progress-tracker.md
Chose an issue #4136 in consensus-specs and asked to assign creating a PR to me.
=> Lada: Cohort 3 Week #3 and #4

Cohort 3/2-progress-tracker.md
[consensus-specs Issue 4136] PR successfully closed.
=> Lada: Cohort 3 Week 4

Cohort 3/2-progress-tracker.md
Currently investigating this issue. I'm checking for excessive retries or event loops causing repeated beacon start requests.
=> Cheryl: Cohort 3 Week 4 Assignment

Cohort 3/1-sessions-tracker.md, Cohort 3/2-progress-tracker.md, Cohort 3/EIPs/Lada-eip-#7732.md
=> Lada: Cohort 3 Week #6

Cohort 3/2-progress-tracker.md
=> IJAY:Cohort 3 week 2

Cohort 3/2-progress-tracker.md
=> IJAY:Cohort 3 week 3 Assignment

Cohort 3/EIPs/Dinah-eip-4938.md
Added changes to my EIP notes and corrected format
=> Dinah: Cohort 3: Week 6

Cohort 3/EIPs/Victoria-eip-1153.md
=> Victoria: Cohort 3 Week 6 Assignment

Cohort 3/2-progress-tracker.md
=> Nabuuma Tracy: Cohort 3 Week2 Assignment

Cohort 3/2-progress-tracker.md
=> IJAY: Cohort 3 week 7 Assignment

Cohort 4/2-progress-tracker.md
=> Beulah-progress-tracker.md
